### PR TITLE
Roadmap for achoz. 

### PR DESCRIPTION
**Pull request by kcubeterm**

### CODE REVIEW

**Review by cauerego — COMMENTED** [review]
i have the impression that video and image stopped working, as i can't find any such results anymore! at least since the beginning of this year.

**Comment by kcubeterm** [comment]
basically, i changed the achoz directory actually. I think you move you all data in some another directory so i just indexed all the sourcecode that was in go directory, that is why there is no image and video there.

**Comment by cauerego** [comment]
that also explains why the results look even more useless! 🤣

do you want me to move the files around? i just wanted one folder removed from the index, as i mentioned elsewhere, but now i think i might want more, since that go folder adds too much meaningless clutter.

**Comment by kcubeterm** [comment]
> do you want me to move the files around? i just wanted one folder removed from the index, as i mentioned elsewhere, but now i think i might want more, since that go folder adds too much meaningless clutter.

No worry . i will add some free videos and audio for showcase.

**Comment by cauerego** [comment]
well, now i am worried!

how about this: can you add another achoz instance with all my files minus that one folder?

perhaps achoz.ahoxus.org/cregox

On January 11, 2022 8:20:26 AM GMT+00:00, Krishna Kanhaiya ***@***.***> wrote:
>> do you want me to move the files around? i just wanted one folder removed from the index, as i mentioned elsewhere, but now i think i might want more, since that go folder adds too much meaningless clutter.
>
>No worry . i will add some free videos and audio for showcase. 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/kcubeterm/achoz/pull/33#issuecomment-1009700800
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- c+sue   ahoxus.org/~cregox    +351 918424479

**Comment by kcubeterm** [comment]
#35 
this feature will solve this problem

**Pull request merged**
