### PR TITLE
Crawler: crawler wont crawl already indexed files.

### PR DESCRIPTION
**Pull request by kcubeterm**

### CODE REVIEW

**Review by cauerego — COMMENTED** [review]
wow, so much work!

i love the new indexedfile and then how it was deleted. 😁

removing code is almost always better than adding code, to fix bugs.

is it fixed now, though?

i miss more comments.

you will miss them too, in the future, when and if you need to touch this code again 1 year from now.

**Comment by kcubeterm** [comment]
> i love the new indexedfile and then how it was deleted.  

That features was added in typesense.js (it's our version of library to handle interaction with typesense engine)

**Comment by cauerego** [comment]
i still can't tell if "crawler won't crawl files which were already indexed" have been fixed though! 🤣

i can see a lot of fixing, but none tells me it the issue is solved.

sometimes we move a lot and better commit the changes, because they are improvements, but aren't finished.

**Comment by kcubeterm** [comment]
There is a misunderstanding!! That fixes commit just mean for deleting and editing title of that page. 

You should see this PR in one commit to understand better. https://github.com/kcubeterm/achoz/commit/3c7d3a8514c6b4f4389c7970675747b89d20ba5c

**Comment by kcubeterm** [comment]
I will try to make more verbose commit next time.

**Pull request merged**
